### PR TITLE
Fix resource classpath for flavoured app projects

### PR DESCRIPTION
**Pull request by davidburstromspotify**
For flavoured app projects, the flavour and built type are nested directories.

### CODE REVIEW

**Comment by davidburstromspotify** [comment]
Would it be possible for you to do a release when this fix is in?

**Comment by davidburstromspotify** [comment]
That'd be most helpful :)

**Comment by koral--** [comment]
Version 0.0.8 published to Gradle Plugin Portal and Maven Central (should be propagated in 2 hours).

**Comment by davidburstromspotify** [comment]
Thank you!

**Pull request merged**
